/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as OrderSuccessRouteImport } from './routes/order.success'
import { Route as OrderCancelRouteImport } from './routes/order.cancel'
import { Route as ApiPublicYoycolSyncRouteImport } from './routes/api/public/yoycol-sync'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicShopifyWebhooksProductsUpdateRouteImport } from './routes/api/public/shopify/webhooks/products-update'
import { Route as ApiPublicShopifyWebhooksProductsDeleteRouteImport } from './routes/api/public/shopify/webhooks/products-delete'
import { Route as ApiPublicShopifyWebhooksProductsCreateRouteImport } from './routes/api/public/shopify/webhooks/products-create'
import { Route as ApiPublicShopifyWebhooksOrdersUpdateRouteImport } from './routes/api/public/shopify/webhooks/orders-update'
import { Route as ApiPublicShopifyWebhooksOrdersCreateRouteImport } from './routes/api/public/shopify/webhooks/orders-create'
import { Route as ApiPublicShopifyWebhooksOrdersCancelledRouteImport } from './routes/api/public/shopify/webhooks/orders-cancelled'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order/success',
  path: '/order/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCancelRoute = OrderCancelRouteImport.update({
  id: '/order/cancel',
  path: '/order/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYoycolSyncRoute = ApiPublicYoycolSyncRouteImport.update({
  id: '/api/public/yoycol-sync',
  path: '/api/public/yoycol-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyWebhooksProductsUpdateRoute =
  ApiPublicShopifyWebhooksProductsUpdateRouteImport.update({
    id: '/api/public/shopify/webhooks/products-update',
    path: '/api/public/shopify/webhooks/products-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyWebhooksProductsDeleteRoute =
  ApiPublicShopifyWebhooksProductsDeleteRouteImport.update({
    id: '/api/public/shopify/webhooks/products-delete',
    path: '/api/public/shopify/webhooks/products-delete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyWebhooksProductsCreateRoute =
  ApiPublicShopifyWebhooksProductsCreateRouteImport.update({
    id: '/api/public/shopify/webhooks/products-create',
    path: '/api/public/shopify/webhooks/products-create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyWebhooksOrdersUpdateRoute =
  ApiPublicShopifyWebhooksOrdersUpdateRouteImport.update({
    id: '/api/public/shopify/webhooks/orders-update',
    path: '/api/public/shopify/webhooks/orders-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyWebhooksOrdersCreateRoute =
  ApiPublicShopifyWebhooksOrdersCreateRouteImport.update({
    id: '/api/public/shopify/webhooks/orders-create',
    path: '/api/public/shopify/webhooks/orders-create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyWebhooksOrdersCancelledRoute =
  ApiPublicShopifyWebhooksOrdersCancelledRouteImport.update({
    id: '/api/public/shopify/webhooks/orders-cancelled',
    path: '/api/public/shopify/webhooks/orders-cancelled',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/order/cancel': typeof OrderCancelRoute
  '/order/success': typeof OrderSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/yoycol-sync': typeof ApiPublicYoycolSyncRoute
  '/api/public/shopify/webhooks/orders-cancelled': typeof ApiPublicShopifyWebhooksOrdersCancelledRoute
  '/api/public/shopify/webhooks/orders-create': typeof ApiPublicShopifyWebhooksOrdersCreateRoute
  '/api/public/shopify/webhooks/orders-update': typeof ApiPublicShopifyWebhooksOrdersUpdateRoute
  '/api/public/shopify/webhooks/products-create': typeof ApiPublicShopifyWebhooksProductsCreateRoute
  '/api/public/shopify/webhooks/products-delete': typeof ApiPublicShopifyWebhooksProductsDeleteRoute
  '/api/public/shopify/webhooks/products-update': typeof ApiPublicShopifyWebhooksProductsUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/order/cancel': typeof OrderCancelRoute
  '/order/success': typeof OrderSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/yoycol-sync': typeof ApiPublicYoycolSyncRoute
  '/api/public/shopify/webhooks/orders-cancelled': typeof ApiPublicShopifyWebhooksOrdersCancelledRoute
  '/api/public/shopify/webhooks/orders-create': typeof ApiPublicShopifyWebhooksOrdersCreateRoute
  '/api/public/shopify/webhooks/orders-update': typeof ApiPublicShopifyWebhooksOrdersUpdateRoute
  '/api/public/shopify/webhooks/products-create': typeof ApiPublicShopifyWebhooksProductsCreateRoute
  '/api/public/shopify/webhooks/products-delete': typeof ApiPublicShopifyWebhooksProductsDeleteRoute
  '/api/public/shopify/webhooks/products-update': typeof ApiPublicShopifyWebhooksProductsUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/order/cancel': typeof OrderCancelRoute
  '/order/success': typeof OrderSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/yoycol-sync': typeof ApiPublicYoycolSyncRoute
  '/api/public/shopify/webhooks/orders-cancelled': typeof ApiPublicShopifyWebhooksOrdersCancelledRoute
  '/api/public/shopify/webhooks/orders-create': typeof ApiPublicShopifyWebhooksOrdersCreateRoute
  '/api/public/shopify/webhooks/orders-update': typeof ApiPublicShopifyWebhooksOrdersUpdateRoute
  '/api/public/shopify/webhooks/products-create': typeof ApiPublicShopifyWebhooksProductsCreateRoute
  '/api/public/shopify/webhooks/products-delete': typeof ApiPublicShopifyWebhooksProductsDeleteRoute
  '/api/public/shopify/webhooks/products-update': typeof ApiPublicShopifyWebhooksProductsUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/shop'
    | '/order/cancel'
    | '/order/success'
    | '/products/$slug'
    | '/api/public/stripe-webhook'
    | '/api/public/yoycol-sync'
    | '/api/public/shopify/webhooks/orders-cancelled'
    | '/api/public/shopify/webhooks/orders-create'
    | '/api/public/shopify/webhooks/orders-update'
    | '/api/public/shopify/webhooks/products-create'
    | '/api/public/shopify/webhooks/products-delete'
    | '/api/public/shopify/webhooks/products-update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/shop'
    | '/order/cancel'
    | '/order/success'
    | '/products/$slug'
    | '/api/public/stripe-webhook'
    | '/api/public/yoycol-sync'
    | '/api/public/shopify/webhooks/orders-cancelled'
    | '/api/public/shopify/webhooks/orders-create'
    | '/api/public/shopify/webhooks/orders-update'
    | '/api/public/shopify/webhooks/products-create'
    | '/api/public/shopify/webhooks/products-delete'
    | '/api/public/shopify/webhooks/products-update'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/shop'
    | '/order/cancel'
    | '/order/success'
    | '/products/$slug'
    | '/api/public/stripe-webhook'
    | '/api/public/yoycol-sync'
    | '/api/public/shopify/webhooks/orders-cancelled'
    | '/api/public/shopify/webhooks/orders-create'
    | '/api/public/shopify/webhooks/orders-update'
    | '/api/public/shopify/webhooks/products-create'
    | '/api/public/shopify/webhooks/products-delete'
    | '/api/public/shopify/webhooks/products-update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRoute
  OrderCancelRoute: typeof OrderCancelRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicYoycolSyncRoute: typeof ApiPublicYoycolSyncRoute
  ApiPublicShopifyWebhooksOrdersCancelledRoute: typeof ApiPublicShopifyWebhooksOrdersCancelledRoute
  ApiPublicShopifyWebhooksOrdersCreateRoute: typeof ApiPublicShopifyWebhooksOrdersCreateRoute
  ApiPublicShopifyWebhooksOrdersUpdateRoute: typeof ApiPublicShopifyWebhooksOrdersUpdateRoute
  ApiPublicShopifyWebhooksProductsCreateRoute: typeof ApiPublicShopifyWebhooksProductsCreateRoute
  ApiPublicShopifyWebhooksProductsDeleteRoute: typeof ApiPublicShopifyWebhooksProductsDeleteRoute
  ApiPublicShopifyWebhooksProductsUpdateRoute: typeof ApiPublicShopifyWebhooksProductsUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/success': {
      id: '/order/success'
      path: '/order/success'
      fullPath: '/order/success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/cancel': {
      id: '/order/cancel'
      path: '/order/cancel'
      fullPath: '/order/cancel'
      preLoaderRoute: typeof OrderCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/yoycol-sync': {
      id: '/api/public/yoycol-sync'
      path: '/api/public/yoycol-sync'
      fullPath: '/api/public/yoycol-sync'
      preLoaderRoute: typeof ApiPublicYoycolSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/products-update': {
      id: '/api/public/shopify/webhooks/products-update'
      path: '/api/public/shopify/webhooks/products-update'
      fullPath: '/api/public/shopify/webhooks/products-update'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksProductsUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/products-delete': {
      id: '/api/public/shopify/webhooks/products-delete'
      path: '/api/public/shopify/webhooks/products-delete'
      fullPath: '/api/public/shopify/webhooks/products-delete'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksProductsDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/products-create': {
      id: '/api/public/shopify/webhooks/products-create'
      path: '/api/public/shopify/webhooks/products-create'
      fullPath: '/api/public/shopify/webhooks/products-create'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksProductsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/orders-update': {
      id: '/api/public/shopify/webhooks/orders-update'
      path: '/api/public/shopify/webhooks/orders-update'
      fullPath: '/api/public/shopify/webhooks/orders-update'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksOrdersUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/orders-create': {
      id: '/api/public/shopify/webhooks/orders-create'
      path: '/api/public/shopify/webhooks/orders-create'
      fullPath: '/api/public/shopify/webhooks/orders-create'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksOrdersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/orders-cancelled': {
      id: '/api/public/shopify/webhooks/orders-cancelled'
      path: '/api/public/shopify/webhooks/orders-cancelled'
      fullPath: '/api/public/shopify/webhooks/orders-cancelled'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksOrdersCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRoute,
  OrderCancelRoute: OrderCancelRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicYoycolSyncRoute: ApiPublicYoycolSyncRoute,
  ApiPublicShopifyWebhooksOrdersCancelledRoute:
    ApiPublicShopifyWebhooksOrdersCancelledRoute,
  ApiPublicShopifyWebhooksOrdersCreateRoute:
    ApiPublicShopifyWebhooksOrdersCreateRoute,
  ApiPublicShopifyWebhooksOrdersUpdateRoute:
    ApiPublicShopifyWebhooksOrdersUpdateRoute,
  ApiPublicShopifyWebhooksProductsCreateRoute:
    ApiPublicShopifyWebhooksProductsCreateRoute,
  ApiPublicShopifyWebhooksProductsDeleteRoute:
    ApiPublicShopifyWebhooksProductsDeleteRoute,
  ApiPublicShopifyWebhooksProductsUpdateRoute:
    ApiPublicShopifyWebhooksProductsUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
